// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	job "github.com/makifbaysal/boilerplates/worker/go-kafka-worker/internal/core/job"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *Store) Get(ctx context.Context, id string) (*job.Job, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *job.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*job.Job, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *job.Job); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Store_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Store_Expecter) Get(ctx interface{}, id interface{}) *Store_Get_Call {
	return &Store_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *Store_Get_Call) Run(run func(ctx context.Context, id string)) *Store_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_Get_Call) Return(_a0 *job.Job, _a1 error) *Store_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_Get_Call) RunAndReturn(run func(context.Context, string) (*job.Job, error)) *Store_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *Store) List(ctx context.Context) ([]*job.Job, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*job.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*job.Job, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*job.Job); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*job.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Store_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) List(ctx interface{}) *Store_List_Call {
	return &Store_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *Store_List_Call) Run(run func(ctx context.Context)) *Store_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_List_Call) Return(_a0 []*job.Job, _a1 error) *Store_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_List_Call) RunAndReturn(run func(context.Context) ([]*job.Job, error)) *Store_List_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function with given fields: ctx, j
func (_m *Store) Record(ctx context.Context, j *job.Job) error {
	ret := _m.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *job.Job) error); ok {
		r0 = rf(ctx, j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type Store_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - j *job.Job
func (_e *Store_Expecter) Record(ctx interface{}, j interface{}) *Store_Record_Call {
	return &Store_Record_Call{Call: _e.mock.On("Record", ctx, j)}
}

func (_c *Store_Record_Call) Run(run func(ctx context.Context, j *job.Job)) *Store_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*job.Job))
	})
	return _c
}

func (_c *Store_Record_Call) Return(_a0 error) *Store_Record_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Record_Call) RunAndReturn(run func(context.Context, *job.Job) error) *Store_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
