sonar.projectKey=android-native
sonar.projectName=Android (Compose) app boilerplate
sonar.sourceEncoding=UTF-8

sonar.sources=app/src/main
sonar.tests=app/src/test
sonar.exclusions=**/build/**,**/generated/**
sonar.java.binaries=app/build/tmp/kotlin-classes/debug
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
