with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/makifbaysal/boilerplates/backend/go-fiber/internal/core/task:
    interfaces:
      Repository:
