package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/makifbaysal/boilerplates/backend/go-fiber/internal/adapter/inbound/graphql/generated"
	"github.com/makifbaysal/boilerplates/backend/go-fiber/internal/adapter/inbound/graphql/model"
	"github.com/makifbaysal/boilerplates/backend/go-fiber/internal/core/task"
)

func toModel(t *task.Task) *model.Task {
	return &model.Task{
		ID:        t.ID,
		Title:     t.Title,
		Done:      t.Done,
		CreatedAt: t.CreatedAt,
		UpdatedAt: t.UpdatedAt,
	}
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, title string) (*model.Task, error) {
	t, err := r.uc.Create(ctx, title)
	if err != nil {
		return nil, err
	}
	return toModel(t), nil
}

// SetTaskDone is the resolver for the setTaskDone field.
func (r *mutationResolver) SetTaskDone(ctx context.Context, id string, done bool) (*model.Task, error) {
	t, err := r.uc.SetDone(ctx, id, done)
	if err != nil {
		return nil, err
	}
	return toModel(t), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	if err := r.uc.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	tasks, err := r.uc.List(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Task, 0, len(tasks))
	for _, t := range tasks {
		out = append(out, toModel(t))
	}
	return out, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	t, err := r.uc.Get(ctx, id)
	if errors.Is(err, task.ErrNotFound) {
		return nil, nil // GraphQL convention: missing-by-id is null, not an error
	}
	if err != nil {
		return nil, err
	}
	return toModel(t), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
