sonar.projectKey=java-spring
sonar.projectName=Spring Boot backend boilerplate
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.exclusions=**/target/**,**/generated/**
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
