sonar.projectKey=ts-react-tailwind-next
sonar.projectName=Next.js + Tailwind frontend boilerplate
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,src/lib/api/generated/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
