sonar.projectKey=go-kafka-worker
sonar.projectName=go-kafka-worker boilerplate
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/mocks/**,**/*_test.go,**/*.pb.go,**/generated/**
sonar.go.coverage.reportPaths=coverage.out
